#!/usr/bin/env bash
# Pack the staged static musl ELFs (scripts/build-gnu.sh) into one `.new`
# archive the board can install with `newpkg install`.
#
#   scripts/pack-gnu.sh [stagedir] [outfile] [version]
#
# The spec is generated from whatever is actually staged, so the package can
# never drift from the build: adding a tool to build-gnu.sh's list is enough.
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
STAGE=$(realpath -m "${1:-$ROOT/ports/stage}")
VER="${3:-9.7}"
OUT=$(realpath -m "${2:-$ROOT/build/packages/gnu-coreutils-$VER-x86_64.new}")

[ -d "$STAGE" ] || { echo "pack-gnu: no staged tools at $STAGE" >&2; exit 1; }

SPEC=$(mktemp)
trap 'rm -f "$SPEC"' EXIT

{
  echo "# generated by scripts/pack-gnu.sh - do not edit"
  echo "name = \"gnu-coreutils\""
  echo "version = \"$VER\""
  echo "arch = \"x86_64\""
  echo "desc = \"GNU coreutils, static musl builds for NEWOS\""
  echo "license = \"GPL-3.0-or-later\""
  echo "maintainer = \"NEWOS\""
  echo "build = \"make gnu && make gnu-pkg\""
  echo "newos-min = \"0.3.0\""
  echo "depends = \"\""
  echo ""
  echo "files:"
  find "$STAGE" -maxdepth 1 -type f | sort | while read -r f; do
    echo "  $f /bin/$(basename "$f") 0755"
  done
} > "$SPEC"

mkdir -p "$(dirname "$OUT")"
python3 "$ROOT/tools/newpkg/newpkg-build.py" "$SPEC" -o "$OUT" --root /
echo "pack-gnu: $(basename "$OUT") ($(stat -c %s "$OUT") bytes)"
